services:
  - type: web
    name: bodega-cat-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app
    pythonVersion: "3.10"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: static/uploads